-- Add project tier and category aggregates to employer_analytics view
-- Generated by GPT-5 Codex on 2025-10-15

begin;

drop view if exists public.employer_analytics;

create or replace view public.employer_analytics with (security_invoker = true) as
select
  e.id as employer_id,
  e.name as employer_name,
  e.abn as employer_abn,
  e.employer_type,
  e.website as employer_website,
  e.email as employer_email,
  e.phone as employer_phone,
  e.estimated_worker_count,
  count(distinct wp.id) as worker_placement_count,
  count(distinct pa.id) as project_assignment_count,
  public.calculate_eba_recency_score(
    jsonb_build_object(
      'fwc_certified_date', cer.fwc_certified_date,
      'eba_lodged_fwc', cer.eba_lodged_fwc,
      'date_eba_signed', cer.date_eba_signed,
      'date_vote_occurred', cer.date_vote_occurred
    )
  ) as eba_recency_score,
  public.get_eba_category(
    jsonb_build_object(
      'fwc_certified_date', cer.fwc_certified_date,
      'eba_lodged_fwc', cer.eba_lodged_fwc,
      'date_eba_signed', cer.date_eba_signed,
      'date_vote_occurred', cer.date_vote_occurred
    )
  ) as eba_category,
  coalesce(array_agg(distinct crt.code) filter (where crt.code is not null), array[]::text[]) as category_roles,
  coalesce(array_agg(distinct tt.code) filter (where tt.code is not null), array[]::text[]) as category_trades,
  bool_or(p.tier = 'tier_1') as has_project_tier_1,
  bool_or(p.tier = 'tier_2') as has_project_tier_2,
  bool_or(p.tier = 'tier_3') as has_project_tier_3
from public.employers e
left join public.company_eba_records cer on cer.employer_id = e.id
left join public.worker_placements wp on wp.employer_id = e.id
left join public.project_assignments pa on pa.employer_id = e.id
left join public.projects p on p.id = pa.project_id
left join public.contractor_role_types crt on crt.id = pa.contractor_role_type_id
left join public.trade_types tt on tt.id = pa.trade_type_id
group by e.id, e.name, e.abn, e.employer_type, e.website, e.email, e.phone, e.estimated_worker_count, cer.id,
         cer.fwc_certified_date, cer.eba_lodged_fwc, cer.date_eba_signed, cer.date_vote_occurred;

comment on view public.employer_analytics is 'Analytics view for employers including aggregates for project counts, categories, and tiers.';

grant select on public.employer_analytics to authenticated;
grant select on public.employer_analytics to anon;
grant select, insert, update, delete on public.employer_analytics to service_role;

commit;

